# Generated by Django 5.0.6 on 2024-07-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_movable',
            field=models.BooleanField(default=True),
        ),
    ]
